"""empty message

Revision ID: 5c7aef842a16
Revises: b64c53b476c7
Create Date: 2023-11-25 17:19:09.519900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7aef842a16'
down_revision = 'b64c53b476c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mother', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('father', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('father')
        batch_op.drop_column('mother')

    # ### end Alembic commands ###
