"""empty message

Revision ID: 7a1470210aca
Revises: 94f8fb07421e
Create Date: 2023-11-22 15:02:49.185627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a1470210aca'
down_revision = '94f8fb07421e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('members_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('members_ibfk_2', 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###
