"""empty message

Revision ID: b64c53b476c7
Revises: 1c0020805dab
Create Date: 2023-11-23 22:47:13.486259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b64c53b476c7'
down_revision = '1c0020805dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deathdate', sa.Date(), nullable=True))
        batch_op.alter_column('alive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('alive',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('deathdate')

    # ### end Alembic commands ###
