"""empty message

Revision ID: e5b858a75c9c
Revises: e05642184a9c
Create Date: 2023-11-22 13:04:46.197087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b858a75c9c'
down_revision = 'e05642184a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    # ### end Alembic commands ###
